---
# tasks file for lb-tier
- name: Install HTTP
  package:
    name: httpie
    state: latest

- name: Install HAProxy
  yum:
    name: haproxy
    state: latest

- name: Start up and enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: true

- name: Deploy HAProxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy
